name: Public-Repo
on: workflow_dispatch

jobs:
  Code:
    runs-on: ubuntu-latest
    steps:
      - name: final-statement
        run: echo "Hi, this is the first step"

      - name: step-finalize
        run: echo "This is the step for final statement"
        
  Build:
   runs-on: ubuntu-latest
   needs: Code
   steps:
     - name: Updating Status
       run: echo "Here is the updated status of the projects"

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Updated status is here
        run: echo "You can find the updated status here"

  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Final update
        run: echo "Here is the final update"

  Monitor:
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
      - name: check the node.js code
        uses: actions/setup-node@v4
        with:
          node-version: '20'

  Live:
    runs-on: ubuntu-latest
    needs: Monitor
    steps:
      - name: Latest update of the deployments
        run: echo "Change the commit and you will get the final update"

      - name: Current Status
        run: echo "Current status is-----Current Status------"

        
