name: Source G-A

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: print a greeting
        run: echo "Hi this is biswadip"

      - name: Show the current server time
        run: date

      - name: Show the current user name
        run: echo $USER

  user-define:
    runs-on: ubuntu-latest
    needs: say-hello

    steps:
      - name: show me who am i?
        run: echo $(whoami)

      - name: Deploying production package
        run: echo "Deploying your application to the server... 🚀 Complete!"

   
