name: Random

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "Hello guys, this side biswadip"

      - name: print the current user
        run: echo "$USER"
      
      - name: print the current date and
        run: echo "Today's date is" $DATE

  say-status:
    runs-on: ubuntu-latest
    needs: say-hello
    steps:
      - name: current status
        run: echo "what is the current status?"
